title: bottifyDev
email: hi@bottify.ru
description: >- # this means to ignore newlines until "baseurl:"
  Разработка и создание ботов и веб сервисов
url: "https://bottify.ru" # the base hostname & protocol for your site
github_username:  bottifyDev

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# controls how big the shell and font looks
font-size: large # options: [small] or [large]
